# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Dev
        run: flyctl deploy --remote-only -a ${{ secrets.FLY_APP_NAME }} --regions ${{ secrets.FLY_REGIONS }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
